version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 2345:5432
    env_file:
      - .env.production
    restart: always
    volumes:
      - volume_postgres:/var/lib/postgres/data

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - 9736:6379
    restart: always
    volumes:
      - volume_redis:/var/lib/redis/data
    env_file:
      - .env.production
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    

  app_node:
    build: .
    container_name: app_node
    ports:
      - 4000:4000
    env_file:
      - .env.production
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run migrate:start"
    depends_on:
      - postgres
      - redis

volumes:
  volume_postgres:
  volume_redis: