on:
  push:
    branches:
      - main

name: Test Docker Compose Build and Run
jobs:
  build_and_run:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create .env.production
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.production

      - name: Build and Run
        run: docker-compose up --build
